# Write a function to compute 5/0 and use try/except to catch the exceptions.


In [1]:
def divide(numerator, denominator):
    try:
        div = numerator/denominator
        return f'Your result for {numerator}/{denominator} = {div}'
    except ZeroDivisionError:
        print('Sorry !! Denominator must not be Zero')

divide(5,0)
divide(5,2)

Sorry !! Denominator must not be Zero


'Your result for 5/2 = 2.5'

# Implement a Python program to generate all sentences where subject is in ["Americans", "Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"]. 
 
Hint: Subject,Verb and Object should be declared in the program as shown below. 
 
subjects=["Americans ","Indians"] verbs=["play","watch"] objects=["Baseball","Cricket"] 
 

Output should come as below: 
 
#Americans  play Baseball.
#Americans  play Cricket.
#Americans  watch Baseball.
#Americans  watch Cricket.
#Indians play Baseball. 
#Indians play Cricket. 
#Indians watch Baseball. 
#Indians watch Cricket. 

In [2]:
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

for sub in subjects:
    for verb in verbs:
        for obj in objects:
            print(f'{sub} {verb} {obj}')

Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


# Write a function so that the columns of the output matrix are powers of the input vector.  
The order of the powers is determined by the increasing boolean argument. Specifically, when              increasing is False, the i-th output column is the input vector raised element-wise to the power                of N - i - 1.  
 
HINT: Such a matrix with a geometric progression in each row is named for Alexandre               Theophile Vandermonde. 

In [3]:
import numpy as np

x = np.array([1, 2, 3, 5])
N = 3
np.vander(x, N)

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]])

In [4]:
np.column_stack([x**(N-1-i) for i in range(N)])

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]], dtype=int32)

In [5]:
x = np.array([1, 2, 3, 5])
np.vander(x)

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [125,  25,   5,   1]])

In [6]:
np.vander(x, increasing=True)

array([[  1,   1,   1,   1],
       [  1,   2,   4,   8],
       [  1,   3,   9,  27],
       [  1,   5,  25, 125]])

In [7]:
np.linalg.det(np.vander(x))

48.00000000000003

In [8]:
(5-3)*(5-2)*(5-1)*(3-2)*(3-1)*(2-1)

48

In [9]:
def vander(x, N=None, increasing=False):
    x = np.asarray(x)
    if x.ndim != 1:
        raise ValueError("x must be a one-dimensional array or sequence.")
    if N is None:
        N = len(x)

    v = np.empty((len(x), N), dtype=np.promote_types(x.dtype, int))
    tmp = v[:, ::-1] if not increasing else v

    if N > 0:
        tmp[:, 0] = 1
    if N > 1:
        tmp[:, 1:] = x[:, None]
        np.multiply.accumulate(tmp[:, 1:], out=tmp[:, 1:], axis=1)

    return v

In [10]:
x = np.array([1, 2, 3, 5])
vander(x)

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [125,  25,   5,   1]])